### Numpy


In [1]:
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
# Python list 
py_list = [1, 2, 3, 4] 
# NumPy array 
np_array = np.array([1, 2, 3, 4]) 
 
print("Python List:", type(py_list)) 
print("NumPy Array:", type(np_array))

Python List: <class 'list'>
NumPy Array: <class 'numpy.ndarray'>


In [ ]:
arr = np.zeros((3, 4))  # 3 rows, 4 columns (rows, columns )
print(arr) 

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
arr = np.ones((2, 3), dtype=int) 
print(arr)

[[1 1 1]
 [1 1 1]]


In [6]:
arr = np.full((2, 2), 7) 
print(arr) 

[[7 7]
 [7 7]]


In [7]:
identity = np.eye(3) 
print(identity) 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
arr = np.arange(0, 10, 2) 
print(arr)  

[0 2 4 6 8]


In [9]:
arr = np.linspace(0, 1, 5) 
print(arr) 

[0.   0.25 0.5  0.75 1.  ]


arange steps by a fixed value (can lead to floating-point issues), while 
linspace divides an interval into n equal parts (more accurate for decimal 
spacing)

In [ ]:
arr = np.random.rand(2, 2) #random numbers between 0 and 1
print(arr) 

[[0.23000342 0.28476505]
 [0.42996947 0.8423742 ]]


In [ ]:
arr = np.random.randint(10, 100, (2, 3)) #random integers between 10 and 100, shape (2,3)
print(arr)

[[58 38 80]
 [45 66 38]]


In [12]:
arr = np.random.randn(3) 
print(arr) 

[ 0.08730688  0.89717144 -0.34530768]


In [13]:
arr = np.empty((2, 2)) 
print(arr)  

[[0.23000342 0.28476505]
 [0.42996947 0.8423742 ]]


### Indexing and Slicing

In [14]:
arr = np.array([10, 20, 30, 40]) 
print(arr[2])     
 
matrix = np.array([[1, 2], [3, 4]]) 
print(matrix[1][0])

30
3


In [ ]:
arr = np.array([10, 20, 30, 40, 50]) 
print(arr[1:4])  # indexing starts from 0, so this will print elements at index 1, 2, and 3; end-1
 
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
print(matrix[0:2, 1:]) #(r:r,c:c)

[20 30 40]
[[2 3]
 [5 6]]


In [16]:
arr = np.array([5, 10, 15, 20]) 
print(arr[-1])    

20


In [17]:
arr = np.array([1, 2, 3, 4, 5]) 
filtered = arr[arr > 3] 
print(filtered) 

[4 5]


In [18]:
arr = np.array([10, 20, 30, 40, 50]) 
print(arr[[1, 3, 4]]) 

[20 40 50]


In [20]:
arr = np.array([0, 1, 2, 3]) 
slice_arr = arr[1:3] #[1,2]
slice_arr[0] = 100 
print(slice_arr)
print(arr) 

[100   2]
[  0 100   2   3]


slice_arr is a view into arr.

It's not an independent copy.

In [56]:
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6]) 
 
print(a + b)  # Output: [5 7 9] 
print(a * b)  # Output: [4 10 18] 
print(a / b)  # Output: [0.25 0.4  0.5 ] 
print(a * 2)   # Output: [2 4 6] 
print(a + 5)   # Output: [6 7 8] 
print(np.sqrt(a))    # Output: [1.         1.41421356 1.73205081]
print(np.exp(a))    # Exponential 
print(np.log(a))    # Natural logarithm
print(np.sum(a))      # Output: 6 
print(np.mean(a))     # Output: 2.0
print(np.std(a))      # Output: 0.816496580927726
print(np.min(a))      # Output: 1 
print(np.max(a))      # Output: 3
print(np.var(a))      # Output: 0.6666 


matrix = np.array([[1, 2, 3], [4, 5, 6]]) 
 
print(np.sum(matrix, axis=0))  # Output: [5 7 9]   (column-wise) 
print(np.sum(matrix, axis=1))  # Output: [6 15]    (row-wise) 
print(np.argmax(matrix))  # Output: 5 (index of the maximum element in the flattened array)

a = np.array([1, 2, 3, 4]) 
print(np.cumsum(a))      
print(np.cumprod(a))  
# [1 3 6 10] 
# [1 2 6 24]


[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[2 4 6]
[6 7 8]
[1.         1.41421356 1.73205081]
[ 2.71828183  7.3890561  20.08553692]
[0.         0.69314718 1.09861229]
6
2.0
0.816496580927726
1
3
0.6666666666666666
[5 7 9]
[ 6 15]
5
[ 1  3  6 10]
[ 1  2  6 24]


In [22]:
 
a = np.array([1, 2, 3]) 
b = 5 
print(a + b)  # Output: [6 7 8] 

[6 7 8]


In [25]:

a = np.array([[1], [2], [3]])  # shape (3,1) 
b = np.array([10, 20, 30])     # shape (3,) 
print(a.shape)
print(b.shape)

(3, 1)
(3,)


In [27]:
#Z-score normalization
data = np.array([10, 20, 30, 40, 50]) 
z = (data - np.mean(data)) / np.std(data) 
print(z)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


### NumPy Array Reshaping & Resizing

In [28]:
a = np.array([1, 2, 3, 4, 5, 6]) 
reshaped = a.reshape((2, 3)) 
print(reshaped) 

[[1 2 3]
 [4 5 6]]


In [29]:
a = np.array([1, 2, 3]) 
a.resize((2, 3)) 
print(a) 

[[1 2 3]
 [0 0 0]]


In [30]:
b = np.array([[1, 2], [3, 4]]) 
 
print(b.ravel())   # Output: [1 2 3 4] 
print(b.flatten()) # Output: [1 2 3 4]

[1 2 3 4]
[1 2 3 4]


Method        Returns    Copy/View 

ravel()   -    1D arr    - View (if possible) 

flatten()   -  1D arr  -   Always a copy 

In [31]:
c = np.array([[1, 2, 3], [4, 5, 6]]) 
print(c.T) 

[[1 4]
 [2 5]
 [3 6]]


In [32]:
d = np.array([[[5]]]) 
print(np.squeeze(d))  

5


In [33]:
e = np.array([1, 2, 3]) 
print(np.expand_dims(e, axis=0))  # shape: (1, 3) 
print(np.expand_dims(e, axis=1))  # shape: (3, 1)

[[1 2 3]]
[[1]
 [2]
 [3]]


In [34]:
x = np.arange(12).reshape((3, 4)) 
print(x.T) 

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


### NumPy Stacking and Splitting 

In [38]:
#hstacking
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6]) 
result = np.hstack((a, b)) 
print(result) 

a = np.array([[1], [2], [3]]) 
b = np.array([[4], [5], [6]]) 
print(np.hstack((a, b))) 

[1 2 3 4 5 6]
[[1 4]
 [2 5]
 [3 6]]


In [39]:
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6]) 
result = np.vstack((a, b)) 
print(result)

[[1 2 3]
 [4 5 6]]


In [40]:
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6]) 
result = np.dstack((a, b)) 
print(result) 

[[[1 4]
  [2 5]
  [3 6]]]


In [47]:
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6]) 
result = np.stack((a, b), axis=1) 
print(result) 

[[1 4]
 [2 5]
 [3 6]]


In [48]:
x = np.arange(8) 
print(np.split(x, 4)) 

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7])]


In [49]:
x = np.arange(10) 
print(np.array_split(x, 3)) 

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [50]:
a = np.array([[1, 2, 3], [4, 5, 6]]) 
print(np.hsplit(a, 3))

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]


In [51]:
a = np.array([[1, 2, 3], [4, 5, 6]]) 
print(np.vsplit(a, 2)) 

[array([[1, 2, 3]]), array([[4, 5, 6]])]
